/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author Abelson
 */
public class Principal extends javax.swing.JFrame {
ControladorPrincipal controler;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        pnPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mInicio = new javax.swing.JMenu();
        mIniSalir = new javax.swing.JMenuItem();
        mMantenimiento = new javax.swing.JMenu();
        mManProducto = new javax.swing.JMenuItem();
        mManCliente = new javax.swing.JMenuItem();
        mManMarca = new javax.swing.JMenuItem();
        mManProveedor = new javax.swing.JMenuItem();
        mAlmacen = new javax.swing.JMenu();
        mAlmEntrada = new javax.swing.JMenuItem();
        mAlmSalida = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mComprobante = new javax.swing.JMenu();
        mComFactura = new javax.swing.JMenuItem();
        mComBoleta = new javax.swing.JMenuItem();
        mComGuiaRemision = new javax.swing.JMenuItem();
        mEntrada = new javax.swing.JMenu();
        mIngIngreso = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu3.setText("File");
        jMenuBar4.add(jMenu3);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1081, Short.MAX_VALUE)
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        mInicio.setText("Inicio");

        mIniSalir.setText("Salir");
        mIniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIniSalirActionPerformed(evt);
            }
        });
        mInicio.add(mIniSalir);

        jMenuBar1.add(mInicio);

        mMantenimiento.setText("Mantenimiento");

        mManProducto.setText("Producto");
        mManProducto.setActionCommand("MantenimientoProducto");
        mMantenimiento.add(mManProducto);

        mManCliente.setText("Cliente");
        mManCliente.setActionCommand("MantenimientoCliente");
        mManCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mManClienteActionPerformed(evt);
            }
        });
        mMantenimiento.add(mManCliente);

        mManMarca.setText("Marca");
        mManMarca.setActionCommand("MantenimientoMarca");
        mMantenimiento.add(mManMarca);

        mManProveedor.setText("Proveedor");
        mManProveedor.setActionCommand("MantenimientoProveedor");
        mManProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mManProveedorActionPerformed(evt);
            }
        });
        mMantenimiento.add(mManProveedor);

        jMenuBar1.add(mMantenimiento);

        mAlmacen.setText("Almacen");
        mAlmacen.setName(""); // NOI18N

        mAlmEntrada.setText("Entrada");
        mAlmEntrada.setActionCommand("RegistrarEntrada");
        mAlmacen.add(mAlmEntrada);

        mAlmSalida.setText("Salida");
        mAlmacen.add(mAlmSalida);

        jMenuItem3.setText("Kardex");
        mAlmacen.add(jMenuItem3);

        jMenuBar1.add(mAlmacen);

        mComprobante.setText("Comprobante");

        mComFactura.setText("Factura");
        mComFactura.setActionCommand("ComprobanteFactura");
        mComprobante.add(mComFactura);

        mComBoleta.setText("Boleta");
        mComBoleta.setActionCommand("ComprobanteBoleta");
        mComprobante.add(mComBoleta);

        mComGuiaRemision.setText("Guia Remisión");
        mComprobante.add(mComGuiaRemision);

        jMenuBar1.add(mComprobante);

        mEntrada.setText("Ingreso");

        mIngIngreso.setText("Nuevo Ingreso");
        mIngIngreso.setActionCommand("NuevoIngreso");
        mEntrada.add(mIngIngreso);

        jMenuBar1.add(mEntrada);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIniSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mIniSalirActionPerformed

    private void mManClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mManClienteActionPerformed
        this.controler.LlamarMantenimientoClientes();
    }//GEN-LAST:event_mManClienteActionPerformed

    private void mManProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mManProveedorActionPerformed
        this.controler.LlamarMantenimientoProveedor();
    }//GEN-LAST:event_mManProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void setControler(ControladorPrincipal controler){
        this.controler=controler;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem mAlmEntrada;
    public javax.swing.JMenuItem mAlmSalida;
    public javax.swing.JMenu mAlmacen;
    public javax.swing.JMenuItem mComBoleta;
    public javax.swing.JMenuItem mComFactura;
    public javax.swing.JMenuItem mComGuiaRemision;
    private javax.swing.JMenu mComprobante;
    private javax.swing.JMenu mEntrada;
    private javax.swing.JMenuItem mIngIngreso;
    private javax.swing.JMenuItem mIniSalir;
    private javax.swing.JMenu mInicio;
    public javax.swing.JMenuItem mManCliente;
    public javax.swing.JMenuItem mManMarca;
    public javax.swing.JMenuItem mManProducto;
    public javax.swing.JMenuItem mManProveedor;
    private javax.swing.JMenu mMantenimiento;
    public javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
